# Generated by Django 5.2.5 on 2025-08-29 15:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cases/updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'case_updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CharityCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('cancer', 'Cancer Treatment'), ('accident', 'Accident Support'), ('acid_attack', 'Acid Attack Recovery'), ('education', 'Education Support'), ('disaster', 'Disaster Relief'), ('medical', 'General Medical'), ('other', 'Other')], max_length=20)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(100)])),
                ('collected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('urgency_flag', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('beneficiary_name', models.CharField(max_length=100)),
                ('beneficiary_age', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_email', models.EmailField(max_length=254)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='cases/images/')),
                ('documents', models.FileField(blank=True, null=True, upload_to='cases/documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
            ],
            options={
                'db_table': 'charity_cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
