# Generated by Django 5.2.5 on 2025-08-29 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caseupdate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charitycase',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='charitycase',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseupdate',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='cases.charitycase'),
        ),
        migrations.AddIndex(
            model_name='charitycase',
            index=models.Index(fields=['category'], name='charity_cas_categor_0d8f76_idx'),
        ),
        migrations.AddIndex(
            model_name='charitycase',
            index=models.Index(fields=['verification_status'], name='charity_cas_verific_81d08a_idx'),
        ),
        migrations.AddIndex(
            model_name='charitycase',
            index=models.Index(fields=['urgency_flag'], name='charity_cas_urgency_2ca12c_idx'),
        ),
        migrations.AddIndex(
            model_name='charitycase',
            index=models.Index(fields=['created_at'], name='charity_cas_created_d138b8_idx'),
        ),
    ]
