# Generated by Django 5.2.5 on 2025-09-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charitycase',
            name='fraud_score',
            field=models.FloatField(blank=True, help_text='AI-computed fraud risk score (0.0 to 1.0)', null=True),
        ),
        migrations.AlterField(
            model_name='charitycase',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
