# Generated by Django 5.2.5 on 2025-08-29 15:44

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecommendationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(help_text="Recommendation score (0-1)")),
                ("algorithm_used", models.CharField(max_length=50)),
                ("recommended_at", models.DateTimeField(auto_now_add=True)),
                ("viewed", models.BooleanField(default=False)),
                ("clicked", models.BooleanField(default=False)),
                ("donated", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "recommendation_history",
                "ordering": ["-recommended_at"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.00"))
                        ],
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            (" ", " "),
                            ("khalti", "Khalti"),
                            ("bank_transfer", "Bank Transfer"),
                            ("cash", "Cash"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(max_length=100, unique=True)),
                (
                    "transaction_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=False)),
                ("donor_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "donor_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("donor_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="cases.charitycase",
                    ),
                ),
            ],
            options={
                "db_table": "donations",
                "ordering": ["-created_at"],
            },
        ),
    ]
