# Generated by Django 5.2.5 on 2025-08-29 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.charitycase'),
        ),
        migrations.AddField(
            model_name='recommendationhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor'], name='donations_donor_i_e43edd_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['case'], name='donations_case_id_964d80_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='donations_status_14f677_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['payment_method'], name='donations_payment_1afce4_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['created_at'], name='donations_created_f10839_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recommendationhistory',
            unique_together={('user', 'case', 'recommended_at')},
        ),
    ]
