# Generated by Django 5.2.5 on 2025-08-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommendationhistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='case',
        ),
        migrations.RemoveField(
            model_name='recommendationhistory',
            name='user',
        ),
    ]
