# Generated by Django 5.2.5 on 2025-08-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_alter_recommendationhistory_unique_together_and_more'),
        ('recommendations', '0003_recommendationhistory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecommendationHistory',
        ),
    ]
