# Generated by Django 5.2.5 on 2025-08-29 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
        ('recommendations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_used', models.CharField(choices=[('content', 'Content-Based'), ('collaborative', 'Collaborative Filtering'), ('clustering', 'Clustering-Based'), ('decision_tree', 'Decision Tree'), ('hybrid', 'Hybrid Algorithm')], max_length=20)),
                ('recommendation_score', models.FloatField()),
                ('clicked', models.BooleanField(default=False)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('donated', models.BooleanField(default=False)),
                ('donated_at', models.DateTimeField(blank=True, null=True)),
                ('shared', models.BooleanField(default=False)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.charitycase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recommendation_history',
            },
        ),
        migrations.AlterField(
            model_name='recommendationfeedback',
            name='recommendation_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.recommendationhistory'),
        ),
        migrations.AddIndex(
            model_name='recommendationhistory',
            index=models.Index(fields=['user', 'created_at'], name='recommendat_user_id_c5fe6f_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationhistory',
            index=models.Index(fields=['algorithm_used'], name='recommendat_algorit_68c210_idx'),
        ),
    ]
